; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

	TITLE	S:\Chris\OneDrive - UAT\C++ Programming II\pete_final\pete_final\Contact.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?__empty_global_delete@@YAXPAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPAXI@Z		; __empty_global_delete
PUBLIC	??0CContact@@QAE@XZ				; CContact::CContact
PUBLIC	??1CContact@@UAE@XZ				; CContact::~CContact
PUBLIC	??_GCContact@@UAEPAXI@Z				; CContact::`scalar deleting destructor'
PUBLIC	??_7CContact@@6B@				; CContact::`vftable'
PUBLIC	??_R4CContact@@6B@				; CContact::`RTTI Complete Object Locator'
PUBLIC	??_R0?AVCContact@@@8				; CContact `RTTI Type Descriptor'
PUBLIC	??_R3CContact@@8				; CContact::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CContact@@8				; CContact::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CContact@@8			; CContact::`RTTI Base Class Descriptor at (0,-1,0,64)'
EXTRN	__purecall:PROC
EXTRN	??3@YAXPAXI@Z:PROC				; operator delete
EXTRN	??0CCustomMenu@@QAE@XZ:PROC			; CCustomMenu::CCustomMenu
EXTRN	??1CCustomMenu@@QAE@XZ:PROC			; CCustomMenu::~CCustomMenu
EXTRN	??_ECContact@@UAEPAXI@Z:PROC			; CContact::`vector deleting destructor'
EXTRN	@__security_check_cookie@4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	___CxxFrameHandler3:PROC
EXTRN	??_7type_info@@6B@:QWORD			; type_info::`vftable'
EXTRN	___security_cookie:DWORD
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT ??_R1A@?0A@EA@CContact@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CContact@@8 DD FLAT:??_R0?AVCContact@@@8	; CContact::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CContact@@8
rdata$r	ENDS
;	COMDAT ??_R2CContact@@8
rdata$r	SEGMENT
??_R2CContact@@8 DD FLAT:??_R1A@?0A@EA@CContact@@8	; CContact::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R3CContact@@8
rdata$r	SEGMENT
??_R3CContact@@8 DD 00H					; CContact::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2CContact@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCContact@@@8
data$r	SEGMENT
??_R0?AVCContact@@@8 DD FLAT:??_7type_info@@6B@		; CContact `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCContact@@', 00H
data$r	ENDS
;	COMDAT ??_R4CContact@@6B@
rdata$r	SEGMENT
??_R4CContact@@6B@ DD 00H				; CContact::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVCContact@@@8
	DD	FLAT:??_R3CContact@@8
rdata$r	ENDS
;	COMDAT ??_7CContact@@6B@
CONST	SEGMENT
??_7CContact@@6B@ DD FLAT:??_R4CContact@@6B@		; CContact::`vftable'
	DD	FLAT:??_ECContact@@UAEPAXI@Z
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
	DD	FLAT:__purecall
CONST	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$??0CContact@@QAE@XZ DD 0ffffffffH
	DD	FLAT:__unwindfunclet$??0CContact@@QAE@XZ$0
	DD	00H
	DD	FLAT:__unwindfunclet$??0CContact@@QAE@XZ$1
	DD	01H
	DD	FLAT:__unwindfunclet$??0CContact@@QAE@XZ$2
__ehfuncinfo$??0CContact@@QAE@XZ DD 019930522H
	DD	03H
	DD	FLAT:__unwindtable$??0CContact@@QAE@XZ
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
xdata$x	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??_GCContact@@UAEPAXI@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
___flags$ = 8						; size = 4
??_GCContact@@UAEPAXI@Z PROC				; CContact::`scalar deleting destructor', COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1CContact@@UAE@XZ			; CContact::~CContact
	mov	eax, DWORD PTR ___flags$[ebp]
	and	eax, 1
	je	SHORT $LN2@scalar
	push	68					; 00000044H
	mov	eax, DWORD PTR _this$[ebp]
	push	eax
	call	??3@YAXPAXI@Z				; operator delete
	add	esp, 8
$LN2@scalar:
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??_GCContact@@UAEPAXI@Z ENDP				; CContact::`scalar deleting destructor'
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File s:\chris\onedrive - uat\c++ programming ii\pete_final\pete_final\contact.cpp
;	COMDAT ??1CContact@@UAE@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
??1CContact@@UAE@XZ PROC				; CContact::~CContact, COMDAT
; _this$ = ecx

; 11   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7CContact@@6B@

; 12   : }

	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 52					; 00000034H
	call	??1CCustomMenu@@QAE@XZ			; CCustomMenu::~CCustomMenu
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 36					; 00000024H
	call	??1CCustomMenu@@QAE@XZ			; CCustomMenu::~CCustomMenu
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 20					; 00000014H
	call	??1CCustomMenu@@QAE@XZ			; CCustomMenu::~CCustomMenu
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	call	??1CCustomMenu@@QAE@XZ			; CCustomMenu::~CCustomMenu
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??1CContact@@UAE@XZ ENDP				; CContact::~CContact
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File s:\chris\onedrive - uat\c++ programming ii\pete_final\pete_final\contact.cpp
;	COMDAT ??0CContact@@QAE@XZ
_TEXT	SEGMENT
_this$ = -20						; size = 4
__$EHRec$ = -12						; size = 12
??0CContact@@QAE@XZ PROC				; CContact::CContact, COMDAT
; _this$ = ecx

; 6    : {

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$??0CContact@@QAE@XZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7CContact@@6B@
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	call	??0CCustomMenu@@QAE@XZ			; CCustomMenu::CCustomMenu
	mov	DWORD PTR __$EHRec$[ebp+8], 0
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 20					; 00000014H
	call	??0CCustomMenu@@QAE@XZ			; CCustomMenu::CCustomMenu
	mov	BYTE PTR __$EHRec$[ebp+8], 1
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 36					; 00000024H
	call	??0CCustomMenu@@QAE@XZ			; CCustomMenu::CCustomMenu
	mov	BYTE PTR __$EHRec$[ebp+8], 2
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 52					; 00000034H
	call	??0CCustomMenu@@QAE@XZ			; CCustomMenu::CCustomMenu

; 7    : }

	mov	DWORD PTR __$EHRec$[ebp+8], -1
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$??0CContact@@QAE@XZ$0:
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	jmp	??1CCustomMenu@@QAE@XZ			; CCustomMenu::~CCustomMenu
__unwindfunclet$??0CContact@@QAE@XZ$1:
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 20					; 00000014H
	jmp	??1CCustomMenu@@QAE@XZ			; CCustomMenu::~CCustomMenu
__unwindfunclet$??0CContact@@QAE@XZ$2:
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 36					; 00000024H
	jmp	??1CCustomMenu@@QAE@XZ			; CCustomMenu::~CCustomMenu
__ehhandler$??0CContact@@QAE@XZ:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-220]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$??0CContact@@QAE@XZ
	jmp	___CxxFrameHandler3
text$x	ENDS
??0CContact@@QAE@XZ ENDP				; CContact::CContact
; Function compile flags: /Odtp /RTCsu /ZI
; File s:\chris\onedrive - uat\c++ programming ii\pete_final\pete_final\contact.cpp
;	COMDAT ?__empty_global_delete@@YAXPAXI@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
___formal$ = 12						; size = 4
?__empty_global_delete@@YAXPAXI@Z PROC			; __empty_global_delete, COMDAT

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAXI@Z ENDP			; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File s:\chris\onedrive - uat\c++ programming ii\pete_final\pete_final\contact.cpp
;	COMDAT ?__empty_global_delete@@YAXPAX@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
?__empty_global_delete@@YAXPAX@Z PROC			; __empty_global_delete, COMDAT

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
